In [1]:
import numpy as np

In [2]:
import numpy.ma as MA

In [6]:
arr2 = array

NameError: name 'array' is not defined

In [7]:
array ([[ 1,  9, 21],
       [29, 41, 51],
       [58, 72,  8]])

NameError: name 'array' is not defined

In [8]:
x = np.random.randint(100, size = 10)

In [9]:
x

array([ 6, 47, 35,  1,  3, 74, 62, 56, 39, 22])

In [10]:
 [x[3],x[7],x[2]]

[1, 56, 35]

In [11]:
ind1 = [3,7,4]
x[ind1]

array([ 1, 56,  3])

In [12]:
ind2 = np.array([[3,7],[4,5]])
x[ind2]

array([[ 1, 56],
       [ 3, 74]])

In [13]:
y = np.arange(12).reshape((3,4))

In [14]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
row =np.array([0,1,2])
col = np.array([2,1,3])
y[row,col]

array([ 2,  5, 11])

In [16]:
y[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [17]:
y[1:,[2,0,3]]

array([[ 6,  4,  7],
       [10,  8, 11]])

In [18]:
mask = np.array([0,0,1,0],dtype = bool)

In [19]:
mask

array([False, False,  True, False])

In [20]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
y[row[:,np.newaxis],mask]

array([[ 2],
       [ 6],
       [10]])

In [22]:
a = np.arange(10)
i = np.array([2,1,8,4])
##a[i] = 99
a[i] -= 10
print(a)

[ 0 -9 -8  3 -6  5  6  7 -2  9]


In [23]:
array_name = np.array(['pine-apple','banana','fig'])

In [24]:
array_name

array(['pine-apple', 'banana', 'fig'], dtype='<U10')

In [25]:
print(np.sort(array_name))

['banana' 'fig' 'pine-apple']


In [26]:
import numpy as np

In [27]:
a1 = np.array([('Anand',2022,8.88),('Anil',2021,9.88) ,('Shubham',2020,8.90)],
              dtype = [('name',(np.str_,10)),('year',np.int32),('cgpa',np.float64)])

In [28]:
print(a1)

[('Anand', 2022, 8.88) ('Anil', 2021, 9.88) ('Shubham', 2020, 8.9 )]


In [30]:
a1 = name

NameError: name 'shubham' is not defined

In [33]:
a1[a1.'name'='shubham']

SyntaxError: invalid syntax (103903860.py, line 1)