In [1]:
type("hello world")

str

In [1]:
import numpy as np

In [2]:
array1 = np.array([11,21,31,41,49])

In [3]:
array1

array([11, 21, 31, 41, 49])

In [5]:
array2 = np.array([[1,9,21],[29,41,51],[58,72,8]])

In [6]:
array2

array([[ 1,  9, 21],
       [29, 41, 51],
       [58, 72,  8]])

In [8]:
array3 = np.array([[15,7,10,-11,20,75],[-3,9,24,1,100,-14]])

In [9]:
array3

array([[ 15,   7,  10, -11,  20,  75],
       [ -3,   9,  24,   1, 100, -14]])

In [11]:
array2.sum()

290

In [12]:
array2.sum(axis=0)

array([ 88, 122,  80])

In [13]:
array2.sum(axis=1)

array([ 31, 121, 138])

In [14]:
np.average(array2)

32.22222222222222

In [16]:
np.average(array3,axis=1)

array([19.33333333, 19.5       ])

In [17]:
np.average(array3,axis=0)

array([ 6. ,  8. , 17. , -5. , 60. , 30.5])

In [19]:
array2.min()

1

In [20]:
array3.mean()

19.416666666666668

In [21]:
array3.mean(1)

array([19.33333333, 19.5       ])

In [1]:
a1=np.array([1,3,5,7])
b1=np.array([90,50,0,30])

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
a1 = np.array([1,3,7,5])
b1 = np.array([90,50,0,30])

In [5]:
c1 = a1+b1

In [6]:
c1

array([91, 53,  7, 35])

In [7]:
a1 = np.array([[12,33,24], [11,21,31]])

In [8]:
a1

array([[12, 33, 24],
       [11, 21, 31]])

In [9]:
b1 =4

In [10]:
b1

4

In [11]:
c1 =a1+b1

In [12]:
c1

array([[16, 37, 28],
       [15, 25, 35]])

In [13]:
arr_random = np.random.randint(10, 50, size = (5, 8))

In [14]:
arr_random

array([[47, 22, 26, 47, 25, 49, 36, 30],
       [44, 33, 10, 44, 36, 18, 36, 25],
       [38, 27, 18, 37, 16, 29, 18, 15],
       [30, 46, 42, 41, 49, 47, 32, 29],
       [12, 12, 13, 11, 43, 44, 45, 30]])

In [15]:
arr_random.ndim

2

In [18]:
import numpy as np

In [22]:
arr2_random = np.random.randint(1,20, size = (3,6,4))

In [23]:
arr2_random

array([[[17,  4,  7,  6],
        [16,  6,  9,  5],
        [16, 10, 17,  2],
        [16, 15,  9,  9],
        [10, 10,  2,  4],
        [ 5,  6,  2,  2]],

       [[17, 18,  7,  3],
        [ 4, 10, 13,  9],
        [ 1, 11, 14, 19],
        [ 4, 16,  3, 14],
        [16,  3, 10,  1],
        [ 6, 17, 18, 10]],

       [[19,  3, 10, 10],
        [19, 16, 14,  7],
        [ 8, 10,  1,  5],
        [10,  6,  7,  3],
        [ 3, 17, 11,  3],
        [ 4, 18, 18, 16]]])

In [24]:
a = np.array([0,2,3,0,1,6,5,2])

In [25]:
np.greater(a,2)

array([False, False,  True, False, False,  True,  True, False])

In [26]:
np.greater_equal(a,2)

array([False,  True,  True, False, False,  True,  True,  True])

In [27]:
a = np.reshape(np.arrange(25),(5,5))

AttributeError: module 'numpy' has no attribute 'arrange'

In [28]:
a =np.reshape(np.arange(25),(5,5))

In [29]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
greater_values = (a>10)

In [31]:
greater_values

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [32]:
even_values = (a%2==0)
odd_values = (a%2==0)

In [33]:
even_values,odd_values

(array([[ True, False,  True, False,  True],
        [False,  True, False,  True, False],
        [ True, False,  True, False,  True],
        [False,  True, False,  True, False],
        [ True, False,  True, False,  True]]),
 array([[ True, False,  True, False,  True],
        [False,  True, False,  True, False],
        [ True, False,  True, False,  True],
        [False,  True, False,  True, False],
        [ True, False,  True, False,  True]]))

In [34]:
b = ~(a%10==0)

In [35]:
b

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [36]:
c= (a%2==0) | (a%3==0)

In [37]:
c

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False,  True]])

In [38]:
import numpy as np
import numpy.ma as MA

In [39]:
array = np.zeros((4,4),dtype = int)

In [40]:
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
array = [2,2] =1

SyntaxError: cannot assign to literal (2475691157.py, line 1)

In [42]:
array[2,2] = 1

In [43]:
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [44]:
array = MA.masked_equal(array,1)

In [45]:
array

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, --, 0],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]],
  fill_value=1)

In [47]:
masked_rows = MA.mask_rows(array)

In [48]:
masked_rows

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [--, --, --, --],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False]],
  fill_value=1)